// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import { toast } from 'sonner';

import { PlasmicHomepage } from "../components/plasmic/evangelisti/PlasmicHomepage";
import { useRouter } from "next/router";

function Homepage() {
  const [formStatus, setFormStatus] = React.useState<'idle' | 'submitting' | 'success' | 'error'>('idle');

  const handleFormSubmit = async (values: any) => {
    const name = values.name?.trim() || '';
    const email = values.email?.trim() || '';
    const message = values.message?.trim() || '';

    // Validation
    if (!name) {
      toast.error('Please enter your name.');
      return;
    }

    if (!email) {
      toast.error('Please enter your email.');
      return;
    }

    if (email.includes(',')) {
      toast.error('Please use a period (.) instead of a comma (,) in your email.');
      return;
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      toast.error('Please enter a valid email address.');
      return;
    }

    if (!message) {
      toast.error('Please enter your message.');
      return;
    }

    setFormStatus('submitting');

    try {
      const response = await fetch('/api/contact', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name,
          email,
          message,
        }),
      });

      const data = await response.json();

      if (data.success) {
        setFormStatus('success');
        toast.success('Thank you! Your message has been sent successfully.');
      } else {
        setFormStatus('error');
        toast.error('Sorry, something went wrong. Please try again later.');
      }
    } catch (error) {
      setFormStatus('error');
      toast.error('Sorry, something went wrong. Please try again later.');
    }
  };

  const dismissToast = () => toast.dismiss();

  return (
    <PageParamsProvider__
      route={useRouter()?.pathname}
      params={useRouter()?.query}
      query={useRouter()?.query}
    >
      <PlasmicHomepage
        form3={{
          onFinish: handleFormSubmit,
        }}
        name={{
          onFocus: dismissToast,
        }}
        email={{
          onFocus: dismissToast,
        }}
        message={{
          onFocus: dismissToast,
        }}
      />
    </PageParamsProvider__>
  );
}

export default Homepage;
