// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import { toast } from 'sonner';

import { PlasmicHomepage } from "../components/plasmic/evangelisti/PlasmicHomepage";
import { useRouter } from "next/router";

function Homepage() {
  const [formStatus, setFormStatus] = React.useState<'idle' | 'submitting' | 'success' | 'error'>('idle');

  const handleFormSubmit = async (values: any) => {
    setFormStatus('submitting');

    try {
      const response = await fetch('/api/contact', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: values.name || '',
          email: values.email || '',
          message: values.message || '',
        }),
      });

      const data = await response.json();

      if (data.success) {
        setFormStatus('success');
        toast.success('Thank you! Your message has been sent successfully.');
      } else {
        setFormStatus('error');
        toast.error('Sorry, something went wrong. Please try again later.');
      }
    } catch (error) {
      setFormStatus('error');
      toast.error('Sorry, something went wrong. Please try again later.');
    }
  };

  return (
    <PageParamsProvider__
      route={useRouter()?.pathname}
      params={useRouter()?.query}
      query={useRouter()?.query}
    >
      <PlasmicHomepage
        form3={{
          onFinish: handleFormSubmit,
        }}
      />
    </PageParamsProvider__>
  );
}

export default Homepage;
