/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: psTfKC1KCEpawf41964R83
// Component: b-UKtaLO3ybb

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { SliderWrapper } from "@plasmicpkgs/react-slick";
import { sliderHelpers as SliderWrapper_Helpers } from "@plasmicpkgs/react-slick";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: psTfKC1KCEpawf41964R83/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: psTfKC1KCEpawf41964R83/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: psTfKC1KCEpawf41964R83/projectcss
import sty from "./PlasmicSwitchingcards.module.css"; // plasmic-import: b-UKtaLO3ybb/css

createPlasmicElementProxy;

export type PlasmicSwitchingcards__VariantMembers = {
  others: "_1st";
};
export type PlasmicSwitchingcards__VariantsArgs = {
  others?: SingleChoiceArg<"_1st">;
};
type VariantPropType = keyof PlasmicSwitchingcards__VariantsArgs;
export const PlasmicSwitchingcards__VariantProps = new Array<VariantPropType>(
  "others"
);

export type PlasmicSwitchingcards__ArgsType = {};
type ArgPropType = keyof PlasmicSwitchingcards__ArgsType;
export const PlasmicSwitchingcards__ArgProps = new Array<ArgPropType>();

export type PlasmicSwitchingcards__OverridesType = {
  root?: Flex__<"div">;
  sliderCarousel2?: Flex__<typeof SliderWrapper>;
  card10?: Flex__<"div">;
  card9?: Flex__<"div">;
  card8?: Flex__<"div">;
};

export interface DefaultSwitchingcardsProps {
  others?: SingleChoiceArg<"_1st">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSwitchingcards__RenderFunc(props: {
  variants: PlasmicSwitchingcards__VariantsArgs;
  args: PlasmicSwitchingcards__ArgsType;
  overrides: PlasmicSwitchingcards__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "others",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.others
      },
      {
        path: "sliderCarousel2.currentSlide",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0,

        refName: "sliderCarousel2",
        onMutate: generateOnMutateForSpec("currentSlide", SliderWrapper_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        { [sty.rootothers__1st]: hasVariant($state, "others", "_1st") }
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox__gZrBz, {
          [sty.freeBoxothers__1st__gZrBz8N26Z]: hasVariant(
            $state,
            "others",
            "_1st"
          )
        })}
      >
        {(() => {
          const child$Props = {
            arrowColor: true ? "rgba(1, 33, 54, 1)" : undefined,
            autoplay: true,
            beforeChange: async (...eventArgs: any) => {
              generateStateOnChangePropForCodeComponents(
                $state,
                "currentSlide",
                ["sliderCarousel2", "currentSlide"],
                SliderWrapper_Helpers
              ).apply(null, eventArgs);
            },
            className: classNames("__wab_instance", sty.sliderCarousel2),
            initialSlide: generateStateValueProp($state, [
              "sliderCarousel2",
              "currentSlide"
            ]),
            ref: ref => {
              $refs["sliderCarousel2"] = ref;
            },
            sliderScopeClassName: sty["sliderCarousel2__slider"]
          };
          initializeCodeComponentStates(
            $state,
            [
              {
                name: "currentSlide",
                plasmicStateName: "sliderCarousel2.currentSlide"
              }
            ],
            [],
            SliderWrapper_Helpers ?? {},
            child$Props
          );

          return (
            <SliderWrapper
              data-plasmic-name={"sliderCarousel2"}
              data-plasmic-override={overrides.sliderCarousel2}
              {...child$Props}
            >
              <div
                className={classNames(projectcss.all, sty.freeBox___1FgfE, {
                  [sty.freeBoxothers__1st___1FgfE8N26Z]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  )
                })}
              >
                <div className={classNames(projectcss.all, sty.freeBox__yfyv6)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__b4Gq)}
                  >
                    <div
                      data-plasmic-name={"card10"}
                      data-plasmic-override={overrides.card10}
                      className={classNames(projectcss.all, sty.card10, {
                        [sty.card10others__1st]: hasVariant(
                          $state,
                          "others",
                          "_1st"
                        )
                      })}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__sr1Q, {
                          [sty.imgothers__1st__sr1Q8N26Z]: hasVariant(
                            $state,
                            "others",
                            "_1st"
                          )
                        })}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/evangelisti/images/rectangle193.svg",
                          fullWidth: 594,
                          fullHeight: 232,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__gQD0
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__j4Gut
                          )}
                        >
                          {"Bridging valuation gaps"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fL8P1
                          )}
                        >
                          {
                            "Call/Put Options, Pragmatic Earn-outs, Vendor Loans and creative risk allocation"
                          }
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__nSjkz, {
                  [sty.freeBoxothers__1st__nSjkz8N26Z]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  )
                })}
              >
                <div className={classNames(projectcss.all, sty.freeBox__jfE5C)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__gdN5)}
                  >
                    <div
                      data-plasmic-name={"card9"}
                      data-plasmic-override={overrides.card9}
                      className={classNames(projectcss.all, sty.card9, {
                        [sty.card9others__1st]: hasVariant(
                          $state,
                          "others",
                          "_1st"
                        )
                      })}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__gfzWz, {
                          [sty.imgothers__1st__gfzWz8N26Z]: hasVariant(
                            $state,
                            "others",
                            "_1st"
                          )
                        })}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/evangelisti/images/rectangle193.svg",
                          fullWidth: 594,
                          fullHeight: 232,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___7Jy5
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wos2P
                          )}
                        >
                          {"Quick Turnaround Times"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___4PJj
                          )}
                        >
                          {
                            "Along the deal lifecycle. From term sheet to definitive agreements"
                          }
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__zwEjF, {
                  [sty.freeBoxothers__1st__zwEjF8N26Z]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  )
                })}
              >
                <div className={classNames(projectcss.all, sty.freeBox__toeJi)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__twhy)}
                  >
                    <div
                      data-plasmic-name={"card8"}
                      data-plasmic-override={overrides.card8}
                      className={classNames(projectcss.all, sty.card8, {
                        [sty.card8others__1st]: hasVariant(
                          $state,
                          "others",
                          "_1st"
                        )
                      })}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___235Zy, {
                          [sty.imgothers__1st___235Zy8N26Z]: hasVariant(
                            $state,
                            "others",
                            "_1st"
                          )
                        })}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/evangelisti/images/rectangle193.svg",
                          fullWidth: 594,
                          fullHeight: 232,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__y8TfC
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__il2E4
                          )}
                        >
                          {"Focused DD & executive outputs"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___064Kw
                          )}
                        >
                          {"locked-box/MAC calibrated to business reality."}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </SliderWrapper>
          );
        })()}
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__dp1Ru)}>
        <div
          className={classNames(projectcss.all, sty.freeBox___0OZob, {
            [sty.freeBoxothers__1st___0OZob8N26Z]: hasVariant(
              $state,
              "others",
              "_1st"
            )
          })}
        >
          {(() => {
            try {
              return $state.sliderCarousel2.currentSlide === 1;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <div className={classNames(projectcss.all, sty.freeBox__eGAl7)}>
              <div className={classNames(projectcss.all, sty.freeBox__zuBrh)} />

              <div className={classNames(projectcss.all, sty.freeBox___2HbA)} />

              <div className={classNames(projectcss.all, sty.freeBox__q9L2Q)} />
            </div>
          ) : null}
          {(() => {
            try {
              return $state.sliderCarousel2.currentSlide === 2;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <div className={classNames(projectcss.all, sty.freeBox__kvOo1)}>
              <div className={classNames(projectcss.all, sty.freeBox__nJuAo)} />

              <div className={classNames(projectcss.all, sty.freeBox__zwQjh)} />

              <div
                className={classNames(projectcss.all, sty.freeBox___25Nhf)}
              />
            </div>
          ) : null}
          {(() => {
            try {
              return $state.sliderCarousel2.currentSlide === 0;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <div className={classNames(projectcss.all, sty.freeBox__xp3Na)}>
              <div className={classNames(projectcss.all, sty.freeBox__uc7RT)} />

              <div className={classNames(projectcss.all, sty.freeBox__bg3Y)} />

              <div className={classNames(projectcss.all, sty.freeBox__rc0D2)} />
            </div>
          ) : null}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "sliderCarousel2", "card10", "card9", "card8"],
  sliderCarousel2: ["sliderCarousel2", "card10", "card9", "card8"],
  card10: ["card10"],
  card9: ["card9"],
  card8: ["card8"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  sliderCarousel2: typeof SliderWrapper;
  card10: "div";
  card9: "div";
  card8: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSwitchingcards__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSwitchingcards__VariantsArgs;
    args?: PlasmicSwitchingcards__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSwitchingcards__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSwitchingcards__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSwitchingcards__ArgProps,
          internalVariantPropNames: PlasmicSwitchingcards__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSwitchingcards__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSwitchingcards";
  } else {
    func.displayName = `PlasmicSwitchingcards.${nodeName}`;
  }
  return func;
}

export const PlasmicSwitchingcards = Object.assign(
  // Top-level PlasmicSwitchingcards renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    sliderCarousel2: makeNodeComponent("sliderCarousel2"),
    card10: makeNodeComponent("card10"),
    card9: makeNodeComponent("card9"),
    card8: makeNodeComponent("card8"),

    // Metadata about props expected for PlasmicSwitchingcards
    internalVariantProps: PlasmicSwitchingcards__VariantProps,
    internalArgProps: PlasmicSwitchingcards__ArgProps
  }
);

export default PlasmicSwitchingcards;
/* prettier-ignore-end */
