/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: psTfKC1KCEpawf41964R83
// Component: dNhLg95F1Nhu

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: psTfKC1KCEpawf41964R83/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: psTfKC1KCEpawf41964R83/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: psTfKC1KCEpawf41964R83/projectcss
import sty from "./PlasmicSectionBox.module.css"; // plasmic-import: dNhLg95F1Nhu/css

import Group322Icon from "./icons/PlasmicIcon__Group322"; // plasmic-import: OAYvWkcwthhC/icon

createPlasmicElementProxy;

export type PlasmicSectionBox__VariantMembers = {
  others:
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_10th"
    | "_11Th"
    | "_8th"
    | "_9th";
};
export type PlasmicSectionBox__VariantsArgs = {
  others?: SingleChoiceArg<
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_10th"
    | "_11Th"
    | "_8th"
    | "_9th"
  >;
};
type VariantPropType = keyof PlasmicSectionBox__VariantsArgs;
export const PlasmicSectionBox__VariantProps = new Array<VariantPropType>(
  "others"
);

export type PlasmicSectionBox__ArgsType = {};
type ArgPropType = keyof PlasmicSectionBox__ArgsType;
export const PlasmicSectionBox__ArgProps = new Array<ArgPropType>();

export type PlasmicSectionBox__OverridesType = {
  root?: Flex__<"div">;
  svg?: Flex__<"svg">;
};

export interface DefaultSectionBoxProps {
  others?: SingleChoiceArg<
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_10th"
    | "_11Th"
    | "_8th"
    | "_9th"
  >;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSectionBox__RenderFunc(props: {
  variants: PlasmicSectionBox__VariantsArgs;
  args: PlasmicSectionBox__ArgsType;
  overrides: PlasmicSectionBox__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "others",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.others
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        {
          [sty.rootothers__10th]: hasVariant($state, "others", "_10th"),
          [sty.rootothers__11Th]: hasVariant($state, "others", "_11Th"),
          [sty.rootothers__1st]: hasVariant($state, "others", "_1st"),
          [sty.rootothers__2nd]: hasVariant($state, "others", "_2nd"),
          [sty.rootothers__3rd]: hasVariant($state, "others", "_3rd"),
          [sty.rootothers__4th]: hasVariant($state, "others", "_4th"),
          [sty.rootothers__5th]: hasVariant($state, "others", "_5th"),
          [sty.rootothers__6th]: hasVariant($state, "others", "_6th"),
          [sty.rootothers__7th]: hasVariant($state, "others", "_7th"),
          [sty.rootothers__8th]: hasVariant($state, "others", "_8th"),
          [sty.rootothers__9th]: hasVariant($state, "others", "_9th")
        }
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__rT3D)}>
        <Group322Icon
          data-plasmic-name={"svg"}
          data-plasmic-override={overrides.svg}
          className={classNames(projectcss.all, sty.svg)}
          role={"img"}
        />

        <div className={classNames(projectcss.all, sty.freeBox___7V1B9)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__n6Qrt
            )}
          >
            <React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ color: "#000000" }}
              >
                {"Why our individual contracts are BEYOND PREMIUM"}
              </span>
            </React.Fragment>
          </div>
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__cswle)}>
        <div className={classNames(projectcss.all, sty.freeBox__dVuQm)}>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__a1Eo2)}
            displayHeight={"50px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"50px"}
            loading={"lazy"}
            src={{
              src: "/plasmic/evangelisti/images/compass1Png.png",
              fullWidth: 44,
              fullHeight: 42,
              aspectRatio: undefined
            }}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__xkygb
            )}
          >
            {
              "We take time to understand your business model and think through risks."
            }
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__onaw)}>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__reM0Z)}
            displayHeight={"50px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"50px"}
            loading={"lazy"}
            src={{
              src: "/plasmic/evangelisti/images/protect1Png.png",
              fullWidth: 44,
              fullHeight: 44,
              aspectRatio: undefined
            }}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__ls7Qv
            )}
          >
            {"We design contracts To Put You \nin the Best Possible Position"}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__ichMw)}>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__hLpz5)}
            displayHeight={"50px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"50px"}
            loading={"lazy"}
            src={{
              src: "/plasmic/evangelisti/images/scalesPng.png",
              fullWidth: 43,
              fullHeight: 43,
              aspectRatio: undefined
            }}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__kvxdK
            )}
          >
            {
              "Sensitivity Applied. No Unnecessary \nProvocation of Your Business Partner"
            }
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__tj5PE)}>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img___7ZCly)}
            displayHeight={"50px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"50px"}
            loading={"lazy"}
            src={{
              src: "/plasmic/evangelisti/images/speed1Png.png",
              fullWidth: 45,
              fullHeight: 45,
              aspectRatio: undefined
            }}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__bx1,
              {
                [sty.textothers__2nd__bx1WVqCv]: hasVariant(
                  $state,
                  "others",
                  "_2nd"
                )
              }
            )}
          >
            {
              "modular regimes (moderate \u2194 aggressive) \nto match Business Partner and situation."
            }
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__skBr1)}>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__h0UwT)}
            displayHeight={"50px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"50px"}
            loading={"lazy"}
            src={{
              src: "/plasmic/evangelisti/images/group62Png.png",
              fullWidth: 42,
              fullHeight: 47,
              aspectRatio: undefined
            }}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__le0V7
            )}
          >
            {
              "Contracts scale with your company and\nserve as a reliable reference."
            }
          </div>
        </div>
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox__jlr86, {
          [sty.freeBoxothers__2nd__jlr86WVqCv]: hasVariant(
            $state,
            "others",
            "_2nd"
          )
        })}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSectionBox__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSectionBox__VariantsArgs;
    args?: PlasmicSectionBox__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSectionBox__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSectionBox__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSectionBox__ArgProps,
          internalVariantPropNames: PlasmicSectionBox__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSectionBox__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSectionBox";
  } else {
    func.displayName = `PlasmicSectionBox.${nodeName}`;
  }
  return func;
}

export const PlasmicSectionBox = Object.assign(
  // Top-level PlasmicSectionBox renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicSectionBox
    internalVariantProps: PlasmicSectionBox__VariantProps,
    internalArgProps: PlasmicSectionBox__ArgProps
  }
);

export default PlasmicSectionBox;
/* prettier-ignore-end */
