/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: psTfKC1KCEpawf41964R83
// Component: WRX8WwTCusqp

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: psTfKC1KCEpawf41964R83/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: psTfKC1KCEpawf41964R83/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: psTfKC1KCEpawf41964R83/projectcss
import sty from "./PlasmicTurningCards.module.css"; // plasmic-import: WRX8WwTCusqp/css

createPlasmicElementProxy;

export type PlasmicTurningCards__VariantMembers = {};
export type PlasmicTurningCards__VariantsArgs = {};
type VariantPropType = keyof PlasmicTurningCards__VariantsArgs;
export const PlasmicTurningCards__VariantProps = new Array<VariantPropType>();

export type PlasmicTurningCards__ArgsType = {};
type ArgPropType = keyof PlasmicTurningCards__ArgsType;
export const PlasmicTurningCards__ArgProps = new Array<ArgPropType>();

export type PlasmicTurningCards__OverridesType = {
  root?: Flex__<"div">;
  group1321315481?: Flex__<"div">;
  group1321315480?: Flex__<"div">;
  group1321315433?: Flex__<"div">;
  rectangle271?: Flex__<"div">;
  bluePoolCapital?: Flex__<"div">;
  asLeadInvestorInThe80MSeriesFOfGyg?: Flex__<"div">;
  image5?: Flex__<"div">;
  group1321315479?: Flex__<"div">;
  group1321315458?: Flex__<"div">;
  rectangle272?: Flex__<"div">;
  marinaCapital?: Flex__<"div">;
  onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech?: Flex__<"div">;
  image9?: Flex__<"div">;
  group1321315478?: Flex__<"div">;
  group1321315457?: Flex__<"div">;
  rectangle273?: Flex__<"div">;
  jetpackStudio?: Flex__<"div">;
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition?: Flex__<"div">;
  group1321315459?: Flex__<"div">;
  rectangle217?: Flex__<"div">;
  image22?: Flex__<"div">;
  _1st?: Flex__<"div">;
  image23?: Flex__<"div">;
  jetpackStudio2?: Flex__<"div">;
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition2?: Flex__<"div">;
  _2nd?: Flex__<"div">;
  image10?: Flex__<"div">;
  jetpackStudio3?: Flex__<"div">;
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition3?: Flex__<"div">;
  _3rd?: Flex__<"div">;
  image6?: Flex__<"div">;
  jetpackStudio4?: Flex__<"div">;
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition4?: Flex__<"div">;
};

export interface DefaultTurningCardsProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTurningCards__RenderFunc(props: {
  variants: PlasmicTurningCards__VariantsArgs;
  args: PlasmicTurningCards__ArgsType;
  overrides: PlasmicTurningCards__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "others",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.others
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__i23Vi)}>
        <div
          data-plasmic-name={"group1321315481"}
          data-plasmic-override={overrides.group1321315481}
          className={classNames(projectcss.all, sty.group1321315481)}
        >
          <div
            data-plasmic-name={"group1321315480"}
            data-plasmic-override={overrides.group1321315480}
            className={classNames(projectcss.all, sty.group1321315480)}
          >
            <div
              data-plasmic-name={"group1321315433"}
              data-plasmic-override={overrides.group1321315433}
              className={classNames(projectcss.all, sty.group1321315433)}
            >
              <div
                data-plasmic-name={"rectangle271"}
                data-plasmic-override={overrides.rectangle271}
                className={classNames(projectcss.all, sty.rectangle271)}
              />

              <div
                data-plasmic-name={"bluePoolCapital"}
                data-plasmic-override={overrides.bluePoolCapital}
                className={classNames(projectcss.all, sty.bluePoolCapital)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yp5Ks
                  )}
                >
                  {"blue pool capital"}
                </div>
              </div>
              <div
                data-plasmic-name={"asLeadInvestorInThe80MSeriesFOfGyg"}
                data-plasmic-override={
                  overrides.asLeadInvestorInThe80MSeriesFOfGyg
                }
                className={classNames(
                  projectcss.all,
                  sty.asLeadInvestorInThe80MSeriesFOfGyg
                )}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cbSpu
                  )}
                >
                  {"as Lead Investor in the\n\u20ac80m Series F of GYG"}
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"image5"}
              data-plasmic-override={overrides.image5}
              className={classNames(projectcss.all, sty.image5)}
            />
          </div>
          <div
            data-plasmic-name={"group1321315479"}
            data-plasmic-override={overrides.group1321315479}
            className={classNames(projectcss.all, sty.group1321315479)}
          >
            <div
              data-plasmic-name={"group1321315458"}
              data-plasmic-override={overrides.group1321315458}
              className={classNames(projectcss.all, sty.group1321315458)}
            >
              <div
                data-plasmic-name={"rectangle272"}
                data-plasmic-override={overrides.rectangle272}
                className={classNames(projectcss.all, sty.rectangle272)}
              />

              <div
                data-plasmic-name={"marinaCapital"}
                data-plasmic-override={overrides.marinaCapital}
                className={classNames(projectcss.all, sty.marinaCapital)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__t07Zi
                  )}
                >
                  {"Marina Capital"}
                </div>
              </div>
              <div
                data-plasmic-name={
                  "onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech"
                }
                data-plasmic-override={
                  overrides.onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech
                }
                className={classNames(
                  projectcss.all,
                  sty.onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech
                )}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1Emm6
                  )}
                >
                  {
                    "on its bespoke founding investment in Rokksta\n- German mining Tech."
                  }
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"image9"}
              data-plasmic-override={overrides.image9}
              className={classNames(projectcss.all, sty.image9)}
            />
          </div>
          <div
            data-plasmic-name={"group1321315478"}
            data-plasmic-override={overrides.group1321315478}
            className={classNames(projectcss.all, sty.group1321315478)}
          >
            <div
              data-plasmic-name={"group1321315457"}
              data-plasmic-override={overrides.group1321315457}
              className={classNames(projectcss.all, sty.group1321315457)}
            >
              <div
                data-plasmic-name={"rectangle273"}
                data-plasmic-override={overrides.rectangle273}
                className={classNames(projectcss.all, sty.rectangle273)}
              />

              <div
                data-plasmic-name={"jetpackStudio"}
                data-plasmic-override={overrides.jetpackStudio}
                className={classNames(projectcss.all, sty.jetpackStudio)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7B0G
                  )}
                >
                  {"Jetpack Studio"}
                </div>
              </div>
              <div
                data-plasmic-name={
                  "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition"
                }
                data-plasmic-override={
                  overrides.gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition
                }
                className={classNames(
                  projectcss.all,
                  sty.gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition
                )}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rm5P3
                  )}
                >
                  {
                    "GmbH in connection with multiple investments such as Merlin Digital Solutions, Rooms Technologies, Glorya , NOBS Nutrition."
                  }
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"group1321315459"}
              data-plasmic-override={overrides.group1321315459}
              className={classNames(projectcss.all, sty.group1321315459)}
            >
              <div
                data-plasmic-name={"rectangle217"}
                data-plasmic-override={overrides.rectangle217}
                className={classNames(projectcss.all, sty.rectangle217)}
              />

              <div
                data-plasmic-name={"image22"}
                data-plasmic-override={overrides.image22}
                className={classNames(projectcss.all, sty.image22)}
              />
            </div>
          </div>
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox___4YMNj)}>
        <div
          data-plasmic-name={"_1st"}
          data-plasmic-override={overrides._1st}
          className={classNames(projectcss.all, sty._1st)}
        >
          <div className={classNames(projectcss.all, sty.freeBox__oxXgZ)}>
            <div
              data-plasmic-name={"image23"}
              data-plasmic-override={overrides.image23}
              className={classNames(projectcss.all, sty.image23)}
            />
          </div>
          <div
            data-plasmic-name={"jetpackStudio2"}
            data-plasmic-override={overrides.jetpackStudio2}
            className={classNames(projectcss.all, sty.jetpackStudio2)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__yEbik
              )}
            >
              {"Jetpack Studio"}
            </div>
          </div>
          <div
            data-plasmic-name={
              "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition2"
            }
            data-plasmic-override={
              overrides.gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition2
            }
            className={classNames(
              projectcss.all,
              sty.gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition2
            )}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mPpTn
              )}
            >
              {
                "GmbH in connection with multiple investments such as Merlin Digital Solutions, Rooms Technologies, Glorya , NOBS Nutrition."
              }
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"_2nd"}
          data-plasmic-override={overrides._2nd}
          className={classNames(projectcss.all, sty._2nd)}
        >
          <div
            data-plasmic-name={"image10"}
            data-plasmic-override={overrides.image10}
            className={classNames(projectcss.all, sty.image10)}
          />

          <div
            data-plasmic-name={"jetpackStudio3"}
            data-plasmic-override={overrides.jetpackStudio3}
            className={classNames(projectcss.all, sty.jetpackStudio3)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ton8Y
              )}
            >
              {"Marina Capital"}
            </div>
          </div>
          <div
            data-plasmic-name={
              "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition3"
            }
            data-plasmic-override={
              overrides.gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition3
            }
            className={classNames(
              projectcss.all,
              sty.gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition3
            )}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__hG1Cb
              )}
            >
              {
                "on its bespoke founding investment in Rokksta\n- German mining Tech."
              }
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"_3rd"}
          data-plasmic-override={overrides._3rd}
          className={classNames(projectcss.all, sty._3rd)}
        >
          <div
            data-plasmic-name={"image6"}
            data-plasmic-override={overrides.image6}
            className={classNames(projectcss.all, sty.image6)}
          />

          <div
            data-plasmic-name={"jetpackStudio4"}
            data-plasmic-override={overrides.jetpackStudio4}
            className={classNames(projectcss.all, sty.jetpackStudio4)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__uZnex
              )}
            >
              {"blue pool capital"}
            </div>
          </div>
          <div
            data-plasmic-name={
              "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition4"
            }
            data-plasmic-override={
              overrides.gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition4
            }
            className={classNames(
              projectcss.all,
              sty.gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition4
            )}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__d23Mh
              )}
            >
              {"as Lead Investor in the\n\u20ac80m Series F of GYG"}
            </div>
          </div>
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__aYxJa)}>
        <div className={classNames(projectcss.all, sty.freeBox__aj3Zh)}>
          <div className={classNames(projectcss.all, sty.freeBox__slKmr)} />

          <div className={classNames(projectcss.all, sty.freeBox__hYzp)} />

          <div className={classNames(projectcss.all, sty.freeBox__k9Ar)} />
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "group1321315481",
    "group1321315480",
    "group1321315433",
    "rectangle271",
    "bluePoolCapital",
    "asLeadInvestorInThe80MSeriesFOfGyg",
    "image5",
    "group1321315479",
    "group1321315458",
    "rectangle272",
    "marinaCapital",
    "onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech",
    "image9",
    "group1321315478",
    "group1321315457",
    "rectangle273",
    "jetpackStudio",
    "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition",
    "group1321315459",
    "rectangle217",
    "image22",
    "_1st",
    "image23",
    "jetpackStudio2",
    "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition2",
    "_2nd",
    "image10",
    "jetpackStudio3",
    "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition3",
    "_3rd",
    "image6",
    "jetpackStudio4",
    "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition4"
  ],
  group1321315481: [
    "group1321315481",
    "group1321315480",
    "group1321315433",
    "rectangle271",
    "bluePoolCapital",
    "asLeadInvestorInThe80MSeriesFOfGyg",
    "image5",
    "group1321315479",
    "group1321315458",
    "rectangle272",
    "marinaCapital",
    "onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech",
    "image9",
    "group1321315478",
    "group1321315457",
    "rectangle273",
    "jetpackStudio",
    "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition",
    "group1321315459",
    "rectangle217",
    "image22"
  ],
  group1321315480: [
    "group1321315480",
    "group1321315433",
    "rectangle271",
    "bluePoolCapital",
    "asLeadInvestorInThe80MSeriesFOfGyg",
    "image5"
  ],
  group1321315433: [
    "group1321315433",
    "rectangle271",
    "bluePoolCapital",
    "asLeadInvestorInThe80MSeriesFOfGyg"
  ],
  rectangle271: ["rectangle271"],
  bluePoolCapital: ["bluePoolCapital"],
  asLeadInvestorInThe80MSeriesFOfGyg: ["asLeadInvestorInThe80MSeriesFOfGyg"],
  image5: ["image5"],
  group1321315479: [
    "group1321315479",
    "group1321315458",
    "rectangle272",
    "marinaCapital",
    "onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech",
    "image9"
  ],
  group1321315458: [
    "group1321315458",
    "rectangle272",
    "marinaCapital",
    "onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech"
  ],
  rectangle272: ["rectangle272"],
  marinaCapital: ["marinaCapital"],
  onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech: [
    "onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech"
  ],
  image9: ["image9"],
  group1321315478: [
    "group1321315478",
    "group1321315457",
    "rectangle273",
    "jetpackStudio",
    "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition",
    "group1321315459",
    "rectangle217",
    "image22"
  ],
  group1321315457: [
    "group1321315457",
    "rectangle273",
    "jetpackStudio",
    "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition"
  ],
  rectangle273: ["rectangle273"],
  jetpackStudio: ["jetpackStudio"],
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition:
    [
      "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition"
    ],
  group1321315459: ["group1321315459", "rectangle217", "image22"],
  rectangle217: ["rectangle217"],
  image22: ["image22"],
  _1st: [
    "_1st",
    "image23",
    "jetpackStudio2",
    "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition2"
  ],
  image23: ["image23"],
  jetpackStudio2: ["jetpackStudio2"],
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition2:
    [
      "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition2"
    ],
  _2nd: [
    "_2nd",
    "image10",
    "jetpackStudio3",
    "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition3"
  ],
  image10: ["image10"],
  jetpackStudio3: ["jetpackStudio3"],
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition3:
    [
      "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition3"
    ],
  _3rd: [
    "_3rd",
    "image6",
    "jetpackStudio4",
    "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition4"
  ],
  image6: ["image6"],
  jetpackStudio4: ["jetpackStudio4"],
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition4:
    [
      "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition4"
    ]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  group1321315481: "div";
  group1321315480: "div";
  group1321315433: "div";
  rectangle271: "div";
  bluePoolCapital: "div";
  asLeadInvestorInThe80MSeriesFOfGyg: "div";
  image5: "div";
  group1321315479: "div";
  group1321315458: "div";
  rectangle272: "div";
  marinaCapital: "div";
  onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech: "div";
  image9: "div";
  group1321315478: "div";
  group1321315457: "div";
  rectangle273: "div";
  jetpackStudio: "div";
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition: "div";
  group1321315459: "div";
  rectangle217: "div";
  image22: "div";
  _1st: "div";
  image23: "div";
  jetpackStudio2: "div";
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition2: "div";
  _2nd: "div";
  image10: "div";
  jetpackStudio3: "div";
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition3: "div";
  _3rd: "div";
  image6: "div";
  jetpackStudio4: "div";
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition4: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTurningCards__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTurningCards__VariantsArgs;
    args?: PlasmicTurningCards__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicTurningCards__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicTurningCards__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTurningCards__ArgProps,
          internalVariantPropNames: PlasmicTurningCards__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTurningCards__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTurningCards";
  } else {
    func.displayName = `PlasmicTurningCards.${nodeName}`;
  }
  return func;
}

export const PlasmicTurningCards = Object.assign(
  // Top-level PlasmicTurningCards renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    group1321315481: makeNodeComponent("group1321315481"),
    group1321315480: makeNodeComponent("group1321315480"),
    group1321315433: makeNodeComponent("group1321315433"),
    rectangle271: makeNodeComponent("rectangle271"),
    bluePoolCapital: makeNodeComponent("bluePoolCapital"),
    asLeadInvestorInThe80MSeriesFOfGyg: makeNodeComponent(
      "asLeadInvestorInThe80MSeriesFOfGyg"
    ),
    image5: makeNodeComponent("image5"),
    group1321315479: makeNodeComponent("group1321315479"),
    group1321315458: makeNodeComponent("group1321315458"),
    rectangle272: makeNodeComponent("rectangle272"),
    marinaCapital: makeNodeComponent("marinaCapital"),
    onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech: makeNodeComponent(
      "onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech"
    ),
    image9: makeNodeComponent("image9"),
    group1321315478: makeNodeComponent("group1321315478"),
    group1321315457: makeNodeComponent("group1321315457"),
    rectangle273: makeNodeComponent("rectangle273"),
    jetpackStudio: makeNodeComponent("jetpackStudio"),
    gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition:
      makeNodeComponent(
        "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition"
      ),
    group1321315459: makeNodeComponent("group1321315459"),
    rectangle217: makeNodeComponent("rectangle217"),
    image22: makeNodeComponent("image22"),
    _1st: makeNodeComponent("_1st"),
    image23: makeNodeComponent("image23"),
    jetpackStudio2: makeNodeComponent("jetpackStudio2"),
    gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition2:
      makeNodeComponent(
        "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition2"
      ),
    _2nd: makeNodeComponent("_2nd"),
    image10: makeNodeComponent("image10"),
    jetpackStudio3: makeNodeComponent("jetpackStudio3"),
    gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition3:
      makeNodeComponent(
        "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition3"
      ),
    _3rd: makeNodeComponent("_3rd"),
    image6: makeNodeComponent("image6"),
    jetpackStudio4: makeNodeComponent("jetpackStudio4"),
    gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition4:
      makeNodeComponent(
        "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition4"
      ),

    // Metadata about props expected for PlasmicTurningCards
    internalVariantProps: PlasmicTurningCards__VariantProps,
    internalArgProps: PlasmicTurningCards__ArgProps
  }
);

export default PlasmicTurningCards;
/* prettier-ignore-end */
