/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: psTfKC1KCEpawf41964R83
// Component: 1s9anK6EM1jR

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: psTfKC1KCEpawf41964R83/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: psTfKC1KCEpawf41964R83/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: psTfKC1KCEpawf41964R83/projectcss
import sty from "./PlasmicSwitchingLettersMobile.module.css"; // plasmic-import: 1s9anK6EM1jR/css

createPlasmicElementProxy;

export type PlasmicSwitchingLettersMobile__VariantMembers = {
  others:
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th"
    | "_11Th"
    | "_12Th"
    | "_13Th";
};
export type PlasmicSwitchingLettersMobile__VariantsArgs = {
  others?: SingleChoiceArg<
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th"
    | "_11Th"
    | "_12Th"
    | "_13Th"
  >;
};
type VariantPropType = keyof PlasmicSwitchingLettersMobile__VariantsArgs;
export const PlasmicSwitchingLettersMobile__VariantProps =
  new Array<VariantPropType>("others");

export type PlasmicSwitchingLettersMobile__ArgsType = {};
type ArgPropType = keyof PlasmicSwitchingLettersMobile__ArgsType;
export const PlasmicSwitchingLettersMobile__ArgProps = new Array<ArgPropType>();

export type PlasmicSwitchingLettersMobile__OverridesType = {
  header3?: Flex__<"div">;
};

export interface DefaultSwitchingLettersMobileProps {
  others?: SingleChoiceArg<
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th"
    | "_11Th"
    | "_12Th"
    | "_13Th"
  >;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSwitchingLettersMobile__RenderFunc(props: {
  variants: PlasmicSwitchingLettersMobile__VariantsArgs;
  args: PlasmicSwitchingLettersMobile__ArgsType;
  overrides: PlasmicSwitchingLettersMobile__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "others",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.others
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"header3"}
      data-plasmic-override={overrides.header3}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.header3,
        { [sty.header3others__13Th]: hasVariant($state, "others", "_13Th") }
      )}
    >
      <p
        className={classNames(
          projectcss.all,
          projectcss.p,
          projectcss.__wab_text,
          sty.p__dCmZb,
          {
            [sty.pothers__1st__dCmZbGMo4]: hasVariant($state, "others", "_1st")
          }
        )}
      >
        <React.Fragment>
          <React.Fragment>{""}</React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__cPmL8,
                {
                  [sty.spanothers__10th__cPmL8C0Ofa]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__cPmL84Uvt3]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__cPmL8AbeYz]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__1st__cPmL8GMo4]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  ),
                  [sty.spanothers__2nd__cPmL8DEx8O]: hasVariant(
                    $state,
                    "others",
                    "_2nd"
                  ),
                  [sty.spanothers__3rd__cPmL8RddDg]: hasVariant(
                    $state,
                    "others",
                    "_3rd"
                  ),
                  [sty.spanothers__4th__cPmL83Fm8S]: hasVariant(
                    $state,
                    "others",
                    "_4th"
                  ),
                  [sty.spanothers__5th__cPmL8ENk9G]: hasVariant(
                    $state,
                    "others",
                    "_5th"
                  ),
                  [sty.spanothers__6th__cPmL85FIpz]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th__cPmL81CzE7]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__cPmL8D9Xmf]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__cPmL8OCpoh]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"I\u2019m not a"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__zj9OL,
                {
                  [sty.spanothers__10th__zj9OLc0Ofa]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__zj9OL4Uvt3]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__zj9OLAbeYz]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__1st__zj9OLGMo4]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  ),
                  [sty.spanothers__2nd__zj9OLdEx8O]: hasVariant(
                    $state,
                    "others",
                    "_2nd"
                  ),
                  [sty.spanothers__3rd__zj9OLRddDg]: hasVariant(
                    $state,
                    "others",
                    "_3rd"
                  ),
                  [sty.spanothers__4th__zj9OL3Fm8S]: hasVariant(
                    $state,
                    "others",
                    "_4th"
                  ),
                  [sty.spanothers__5th__zj9OLeNk9G]: hasVariant(
                    $state,
                    "others",
                    "_5th"
                  ),
                  [sty.spanothers__6th__zj9OL5FIpz]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th__zj9OL1CzE7]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__zj9OLd9Xmf]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__zj9OLoCpoh]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"traditional lawyer."}
            </span>
          }
          <React.Fragment>{""}</React.Fragment>
        </React.Fragment>
      </p>
      <p
        className={classNames(
          projectcss.all,
          projectcss.p,
          projectcss.__wab_text,
          sty.p__vEbBs,
          {
            [sty.pothers__13Th__vEbBsyQeVz]: hasVariant(
              $state,
              "others",
              "_13Th"
            ),
            [sty.pothers__1st__vEbBsGMo4]: hasVariant($state, "others", "_1st")
          }
        )}
      >
        <React.Fragment>
          <React.Fragment>{""}</React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__z9JVo,
                {
                  [sty.spanothers__10th__z9JVoc0Ofa]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__z9JVo4Uvt3]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__z9JVoAbeYz]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__1st__z9JVoGMo4]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  ),
                  [sty.spanothers__3rd__z9JVoRddDg]: hasVariant(
                    $state,
                    "others",
                    "_3rd"
                  ),
                  [sty.spanothers__4th__z9JVo3Fm8S]: hasVariant(
                    $state,
                    "others",
                    "_4th"
                  ),
                  [sty.spanothers__5th__z9JVoeNk9G]: hasVariant(
                    $state,
                    "others",
                    "_5th"
                  ),
                  [sty.spanothers__6th__z9JVo5FIpz]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th__z9JVo1CzE7]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__z9JVoD9Xmf]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__z9JVoOCpoh]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"Pragmatic,"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__hwlum,
                {
                  [sty.spanothers__10th__hwlumc0Ofa]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__hwlum4Uvt3]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__hwlumAbeYz]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__1st__hwlumGMo4]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  ),
                  [sty.spanothers__4th__hwlum3Fm8S]: hasVariant(
                    $state,
                    "others",
                    "_4th"
                  ),
                  [sty.spanothers__5th__hwlumeNk9G]: hasVariant(
                    $state,
                    "others",
                    "_5th"
                  ),
                  [sty.spanothers__6th__hwlum5FIpz]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th__hwlum1CzE7]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__hwlumD9Xmf]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__hwlumOCpoh]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"entrepreneurial "}
            </span>
          }
          <React.Fragment>{""}</React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span___3I3KX,
                {
                  [sty.spanothers__10th___3I3KXc0Ofa]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th___3I3KX4Uvt3]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th___3I3KXAbeYz]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__5th___3I3KXeNk9G]: hasVariant(
                    $state,
                    "others",
                    "_5th"
                  ),
                  [sty.spanothers__6th___3I3KX5FIpz]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th___3I3KX1CzE7]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th___3I3KXd9Xmf]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th___3I3KXoCpoh]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"legal support"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__cORjC,
                {
                  [sty.spanothers__10th__cORjCc0Ofa]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__cORjC4Uvt3]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__cORjCAbeYz]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__6th__cORjC5FIpz]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th__cORjC1CzE7]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__cORjCd9Xmf]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__cORjCoCpoh]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"with heart"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__yu8Xx,
                {
                  [sty.spanothers__10th__yu8Xxc0Ofa]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__yu8Xx4Uvt3]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__yu8XxAbeYz]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__7th__yu8Xx1CzE7]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__yu8XxD9Xmf]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__yu8XxOCpoh]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"and soul. "}
            </span>
          }
          <React.Fragment>{""}</React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__dr6NH,
                {
                  [sty.spanothers__10th__dr6NHc0Ofa]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__dr6NH4Uvt3]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__dr6NHAbeYz]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__8th__dr6NHd9Xmf]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__dr6NHoCpoh]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"Focused on"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span___2YWpk,
                {
                  [sty.spanothers__10th___2YWpkc0Ofa]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th___2YWpk4Uvt3]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th___2YWpkAbeYz]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__9th___2YWpkOCpoh]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"clear solutions"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__jCzzo,
                {
                  [sty.spanothers__10th__jCzzoc0Ofa]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__jCzzo4Uvt3]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__jCzzoAbeYz]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__1st__jCzzoGMo4]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  )
                }
              )}
            >
              {"that move"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span___9Olsg,
                {
                  [sty.spanothers__11Th___9Olsg4Uvt3]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th___9OlsgAbeYz]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  )
                }
              )}
            >
              {"your business"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__zlWy8,
                {
                  [sty.spanothers__12Th__zlWy8AbeYz]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  )
                }
              )}
            >
              {"forward"}
            </span>
          }
          <React.Fragment>{""}</React.Fragment>
        </React.Fragment>
      </p>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  header3: ["header3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  header3: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSwitchingLettersMobile__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSwitchingLettersMobile__VariantsArgs;
    args?: PlasmicSwitchingLettersMobile__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSwitchingLettersMobile__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSwitchingLettersMobile__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSwitchingLettersMobile__ArgProps,
          internalVariantPropNames: PlasmicSwitchingLettersMobile__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSwitchingLettersMobile__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "header3") {
    func.displayName = "PlasmicSwitchingLettersMobile";
  } else {
    func.displayName = `PlasmicSwitchingLettersMobile.${nodeName}`;
  }
  return func;
}

export const PlasmicSwitchingLettersMobile = Object.assign(
  // Top-level PlasmicSwitchingLettersMobile renders the root element
  makeNodeComponent("header3"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicSwitchingLettersMobile
    internalVariantProps: PlasmicSwitchingLettersMobile__VariantProps,
    internalArgProps: PlasmicSwitchingLettersMobile__ArgProps
  }
);

export default PlasmicSwitchingLettersMobile;
/* prettier-ignore-end */
