/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: psTfKC1KCEpawf41964R83
// Component: CzpJjqkoJlCS

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: psTfKC1KCEpawf41964R83/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: psTfKC1KCEpawf41964R83/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: psTfKC1KCEpawf41964R83/projectcss
import sty from "./PlasmicMijack.module.css"; // plasmic-import: CzpJjqkoJlCS/css

import Group322Icon from "./icons/PlasmicIcon__Group322"; // plasmic-import: OAYvWkcwthhC/icon

createPlasmicElementProxy;

export type PlasmicMijack__VariantMembers = {
  others:
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th"
    | "_11Th"
    | "_12Th";
};
export type PlasmicMijack__VariantsArgs = {
  others?: SingleChoiceArg<
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th"
    | "_11Th"
    | "_12Th"
  >;
};
type VariantPropType = keyof PlasmicMijack__VariantsArgs;
export const PlasmicMijack__VariantProps = new Array<VariantPropType>("others");

export type PlasmicMijack__ArgsType = {};
type ArgPropType = keyof PlasmicMijack__ArgsType;
export const PlasmicMijack__ArgProps = new Array<ArgPropType>();

export type PlasmicMijack__OverridesType = {
  root?: Flex__<"div">;
  svg?: Flex__<"svg">;
  image1?: Flex__<"div">;
  image2?: Flex__<"div">;
};

export interface DefaultMijackProps {
  others?: SingleChoiceArg<
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th"
    | "_11Th"
    | "_12Th"
  >;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMijack__RenderFunc(props: {
  variants: PlasmicMijack__VariantsArgs;
  args: PlasmicMijack__ArgsType;
  overrides: PlasmicMijack__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "others",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.others
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        {
          [sty.rootothers__10th]: hasVariant($state, "others", "_10th"),
          [sty.rootothers__11Th]: hasVariant($state, "others", "_11Th"),
          [sty.rootothers__1st]: hasVariant($state, "others", "_1st"),
          [sty.rootothers__2nd]: hasVariant($state, "others", "_2nd"),
          [sty.rootothers__3rd]: hasVariant($state, "others", "_3rd"),
          [sty.rootothers__4th]: hasVariant($state, "others", "_4th"),
          [sty.rootothers__5th]: hasVariant($state, "others", "_5th"),
          [sty.rootothers__6th]: hasVariant($state, "others", "_6th"),
          [sty.rootothers__7th]: hasVariant($state, "others", "_7th"),
          [sty.rootothers__8th]: hasVariant($state, "others", "_8th"),
          [sty.rootothers__9th]: hasVariant($state, "others", "_9th")
        }
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox___1D55X)}>
        <div className={classNames(projectcss.all, sty.freeBox__lDcBx)}>
          <div className={classNames(projectcss.all, sty.freeBox__g5REu)}>
            <Group322Icon
              data-plasmic-name={"svg"}
              data-plasmic-override={overrides.svg}
              className={classNames(projectcss.all, sty.svg)}
              role={"img"}
            />

            <div className={classNames(projectcss.all, sty.freeBox__btjYc)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cAi1N
                )}
              >
                {"Case study"}
              </div>
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"image1"}
          data-plasmic-override={overrides.image1}
          className={classNames(projectcss.all, sty.image1)}
        >
          <div
            data-plasmic-name={"image2"}
            data-plasmic-override={overrides.image2}
            className={classNames(projectcss.all, sty.image2)}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__haIeN
            )}
          >
            <React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ fontWeight: 700 }}
              >
                {"Mi-Jack Europe GmbH (formerly Yardeye)"}
              </span>
              <React.Fragment>
                {
                  "\nTrusted advisor for operational contracts, \nUS/Europe group structures, HR topics and all things IP"
                }
              </React.Fragment>
            </React.Fragment>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg", "image1", "image2"],
  svg: ["svg"],
  image1: ["image1", "image2"],
  image2: ["image2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
  image1: "div";
  image2: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMijack__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMijack__VariantsArgs;
    args?: PlasmicMijack__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicMijack__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicMijack__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMijack__ArgProps,
          internalVariantPropNames: PlasmicMijack__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMijack__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMijack";
  } else {
    func.displayName = `PlasmicMijack.${nodeName}`;
  }
  return func;
}

export const PlasmicMijack = Object.assign(
  // Top-level PlasmicMijack renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    image1: makeNodeComponent("image1"),
    image2: makeNodeComponent("image2"),

    // Metadata about props expected for PlasmicMijack
    internalVariantProps: PlasmicMijack__VariantProps,
    internalArgProps: PlasmicMijack__ArgProps
  }
);

export default PlasmicMijack;
/* prettier-ignore-end */
