/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: psTfKC1KCEpawf41964R83
// Component: -FEwWYTTtKo6

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: psTfKC1KCEpawf41964R83/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: psTfKC1KCEpawf41964R83/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: psTfKC1KCEpawf41964R83/projectcss
import sty from "./PlasmicStep2.module.css"; // plasmic-import: -FEwWYTTtKo6/css

createPlasmicElementProxy;

export type PlasmicStep2__VariantMembers = {
  others: "_1st" | "_2nd" | "_3rd" | "_4th" | "_5th" | "_6th" | "_7th";
};
export type PlasmicStep2__VariantsArgs = {
  others?: SingleChoiceArg<
    "_1st" | "_2nd" | "_3rd" | "_4th" | "_5th" | "_6th" | "_7th"
  >;
};
type VariantPropType = keyof PlasmicStep2__VariantsArgs;
export const PlasmicStep2__VariantProps = new Array<VariantPropType>("others");

export type PlasmicStep2__ArgsType = {};
type ArgPropType = keyof PlasmicStep2__ArgsType;
export const PlasmicStep2__ArgProps = new Array<ArgPropType>();

export type PlasmicStep2__OverridesType = {
  step1?: Flex__<"div">;
  text?: Flex__<"div">;
};

export interface DefaultStep2Props {
  others?: SingleChoiceArg<
    "_1st" | "_2nd" | "_3rd" | "_4th" | "_5th" | "_6th" | "_7th"
  >;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicStep2__RenderFunc(props: {
  variants: PlasmicStep2__VariantsArgs;
  args: PlasmicStep2__ArgsType;
  overrides: PlasmicStep2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "others",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.others
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"step1"}
      data-plasmic-override={overrides.step1}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.step1,
        {
          [sty.step1others__1st]: hasVariant($state, "others", "_1st"),
          [sty.step1others__2nd]: hasVariant($state, "others", "_2nd"),
          [sty.step1others__3rd]: hasVariant($state, "others", "_3rd"),
          [sty.step1others__4th]: hasVariant($state, "others", "_4th"),
          [sty.step1others__5th]: hasVariant($state, "others", "_5th"),
          [sty.step1others__6th]: hasVariant($state, "others", "_6th"),
          [sty.step1others__7th]: hasVariant($state, "others", "_7th")
        }
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox___2ElK4, {
          [sty.freeBoxothers__7th___2ElK47Gz8F]: hasVariant(
            $state,
            "others",
            "_7th"
          )
        })}
      >
        <div className={classNames(projectcss.all, sty.freeBox__s6GL5)}>
          <div
            data-plasmic-name={"text"}
            data-plasmic-override={overrides.text}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text
            )}
          >
            <React.Fragment>
              <React.Fragment>{""}</React.Fragment>
              {
                <span
                  className={classNames(
                    projectcss.all,
                    projectcss.span,
                    projectcss.__wab_text,
                    projectcss.plasmic_default__inline,
                    sty.span__zbjez,
                    {
                      [sty.spanothers__1st__zbjezTmQ3]: hasVariant(
                        $state,
                        "others",
                        "_1st"
                      ),
                      [sty.spanothers__2nd__zbjezaMv6K]: hasVariant(
                        $state,
                        "others",
                        "_2nd"
                      ),
                      [sty.spanothers__3rd__zbjezO111O]: hasVariant(
                        $state,
                        "others",
                        "_3rd"
                      ),
                      [sty.spanothers__4th__zbjezAOfSz]: hasVariant(
                        $state,
                        "others",
                        "_4th"
                      ),
                      [sty.spanothers__5th__zbjezFpi94]: hasVariant(
                        $state,
                        "others",
                        "_5th"
                      ),
                      [sty.spanothers__6th__zbjez6JcnC]: hasVariant(
                        $state,
                        "others",
                        "_6th"
                      ),
                      [sty.spanothers__7th__zbjez7Gz8F]: hasVariant(
                        $state,
                        "others",
                        "_7th"
                      )
                    }
                  )}
                >
                  {"Deals rarely"}
                </span>
              }
              <React.Fragment> </React.Fragment>
              {
                <span
                  className={classNames(
                    projectcss.all,
                    projectcss.span,
                    projectcss.__wab_text,
                    projectcss.plasmic_default__inline,
                    sty.span__heHjy,
                    {
                      [sty.spanothers__2nd__heHjyaMv6K]: hasVariant(
                        $state,
                        "others",
                        "_2nd"
                      ),
                      [sty.spanothers__3rd__heHjyO111O]: hasVariant(
                        $state,
                        "others",
                        "_3rd"
                      ),
                      [sty.spanothers__4th__heHjyAOfSz]: hasVariant(
                        $state,
                        "others",
                        "_4th"
                      ),
                      [sty.spanothers__5th__heHjyFpi94]: hasVariant(
                        $state,
                        "others",
                        "_5th"
                      ),
                      [sty.spanothers__6th__heHjy6JcnC]: hasVariant(
                        $state,
                        "others",
                        "_6th"
                      )
                    }
                  )}
                >
                  {"fail on"}
                </span>
              }
              <React.Fragment> </React.Fragment>
              {
                <span
                  className={classNames(
                    projectcss.all,
                    projectcss.span,
                    projectcss.__wab_text,
                    projectcss.plasmic_default__inline,
                    sty.span__cvvWe,
                    {
                      [sty.spanothers__3rd__cvvWeO111O]: hasVariant(
                        $state,
                        "others",
                        "_3rd"
                      ),
                      [sty.spanothers__4th__cvvWeAOfSz]: hasVariant(
                        $state,
                        "others",
                        "_4th"
                      ),
                      [sty.spanothers__5th__cvvWeFpi94]: hasVariant(
                        $state,
                        "others",
                        "_5th"
                      ),
                      [sty.spanothers__6th__cvvWe6JcnC]: hasVariant(
                        $state,
                        "others",
                        "_6th"
                      )
                    }
                  )}
                >
                  {"legal provisions."}
                </span>
              }
              <React.Fragment> </React.Fragment>
              {
                <span
                  className={classNames(
                    projectcss.all,
                    projectcss.span,
                    projectcss.__wab_text,
                    projectcss.plasmic_default__inline,
                    sty.span__xQwh,
                    {
                      [sty.spanothers__4th__xQwhAOfSz]: hasVariant(
                        $state,
                        "others",
                        "_4th"
                      ),
                      [sty.spanothers__5th__xQwhFpi94]: hasVariant(
                        $state,
                        "others",
                        "_5th"
                      ),
                      [sty.spanothers__6th__xQwh6JcnC]: hasVariant(
                        $state,
                        "others",
                        "_6th"
                      )
                    }
                  )}
                >
                  {"They stall"}
                </span>
              }
              <React.Fragment> </React.Fragment>
              {
                <span
                  className={classNames(
                    projectcss.all,
                    projectcss.span,
                    projectcss.__wab_text,
                    projectcss.plasmic_default__inline,
                    sty.span___0Uu9Y,
                    {
                      [sty.spanothers__5th___0Uu9Yfpi94]: hasVariant(
                        $state,
                        "others",
                        "_5th"
                      ),
                      [sty.spanothers__6th___0Uu9Y6JcnC]: hasVariant(
                        $state,
                        "others",
                        "_6th"
                      )
                    }
                  )}
                >
                  {"because of"}
                </span>
              }
              <React.Fragment> </React.Fragment>
              {
                <span
                  className={classNames(
                    projectcss.all,
                    projectcss.span,
                    projectcss.__wab_text,
                    projectcss.plasmic_default__inline,
                    sty.span__gqvoX,
                    {
                      [sty.spanothers__6th__gqvoX6JcnC]: hasVariant(
                        $state,
                        "others",
                        "_6th"
                      )
                    }
                  )}
                >
                  {"mindset: over-"}
                </span>
              }
              <React.Fragment>{""}</React.Fragment>
            </React.Fragment>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  step1: ["step1", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  step1: "div";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStep2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStep2__VariantsArgs;
    args?: PlasmicStep2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicStep2__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicStep2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicStep2__ArgProps,
          internalVariantPropNames: PlasmicStep2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStep2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "step1") {
    func.displayName = "PlasmicStep2";
  } else {
    func.displayName = `PlasmicStep2.${nodeName}`;
  }
  return func;
}

export const PlasmicStep2 = Object.assign(
  // Top-level PlasmicStep2 renders the root element
  makeNodeComponent("step1"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicStep2
    internalVariantProps: PlasmicStep2__VariantProps,
    internalArgProps: PlasmicStep2__ArgProps
  }
);

export default PlasmicStep2;
/* prettier-ignore-end */
