/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: psTfKC1KCEpawf41964R83

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsjAd6DNsnouYe } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jAD6DNsnouYe/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsjAd6DNsnouYe
});
