/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: psTfKC1KCEpawf41964R83
// Component: jzvN_9UyJix7

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: psTfKC1KCEpawf41964R83/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: psTfKC1KCEpawf41964R83/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: psTfKC1KCEpawf41964R83/projectcss
import sty from "./PlasmicSwitchingLetters.module.css"; // plasmic-import: jzvN_9UyJix7/css

createPlasmicElementProxy;

export type PlasmicSwitchingLetters__VariantMembers = {
  others:
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th"
    | "_11Th"
    | "_12Th"
    | "_13Th";
};
export type PlasmicSwitchingLetters__VariantsArgs = {
  others?: SingleChoiceArg<
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th"
    | "_11Th"
    | "_12Th"
    | "_13Th"
  >;
};
type VariantPropType = keyof PlasmicSwitchingLetters__VariantsArgs;
export const PlasmicSwitchingLetters__VariantProps = new Array<VariantPropType>(
  "others"
);

export type PlasmicSwitchingLetters__ArgsType = {};
type ArgPropType = keyof PlasmicSwitchingLetters__ArgsType;
export const PlasmicSwitchingLetters__ArgProps = new Array<ArgPropType>();

export type PlasmicSwitchingLetters__OverridesType = {
  header3?: Flex__<"div">;
};

export interface DefaultSwitchingLettersProps {
  others?: SingleChoiceArg<
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th"
    | "_11Th"
    | "_12Th"
    | "_13Th"
  >;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSwitchingLetters__RenderFunc(props: {
  variants: PlasmicSwitchingLetters__VariantsArgs;
  args: PlasmicSwitchingLetters__ArgsType;
  overrides: PlasmicSwitchingLetters__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "others",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.others
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"header3"}
      data-plasmic-override={overrides.header3}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.header3,
        { [sty.header3others__13Th]: hasVariant($state, "others", "_13Th") }
      )}
    >
      <p
        className={classNames(
          projectcss.all,
          projectcss.p,
          projectcss.__wab_text,
          sty.p__xarR,
          {
            [sty.pothers__1st__xarRe5Ktz]: hasVariant($state, "others", "_1st")
          }
        )}
      >
        <React.Fragment>
          <React.Fragment>{""}</React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__jCmPh,
                {
                  [sty.spanothers__10th__jCmPHqLFfT]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__jCmPh2MkTs]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__jCmPhnKavM]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__1st__jCmPhe5Ktz]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  ),
                  [sty.spanothers__2nd__jCmPHleJ3E]: hasVariant(
                    $state,
                    "others",
                    "_2nd"
                  ),
                  [sty.spanothers__3rd__jCmPHibNO]: hasVariant(
                    $state,
                    "others",
                    "_3rd"
                  ),
                  [sty.spanothers__4th__jCmPHnApJo]: hasVariant(
                    $state,
                    "others",
                    "_4th"
                  ),
                  [sty.spanothers__5th__jCmPHhEoGp]: hasVariant(
                    $state,
                    "others",
                    "_5th"
                  ),
                  [sty.spanothers__6th__jCmPhXkkIk]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th__jCmPHn7Brb]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__jCmPHtQmee]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__jCmPhiEgyQ]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"I\u2019m not a"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__pri2G,
                {
                  [sty.spanothers__10th__pri2GqLFfT]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__pri2G2MkTs]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__pri2GnKavM]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__1st__pri2Ge5Ktz]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  ),
                  [sty.spanothers__2nd__pri2GleJ3E]: hasVariant(
                    $state,
                    "others",
                    "_2nd"
                  ),
                  [sty.spanothers__3rd__pri2GibNO]: hasVariant(
                    $state,
                    "others",
                    "_3rd"
                  ),
                  [sty.spanothers__4th__pri2GnApJo]: hasVariant(
                    $state,
                    "others",
                    "_4th"
                  ),
                  [sty.spanothers__5th__pri2GhEoGp]: hasVariant(
                    $state,
                    "others",
                    "_5th"
                  ),
                  [sty.spanothers__6th__pri2GXkkIk]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th__pri2Gn7Brb]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__pri2GtQmee]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__pri2GiEgyQ]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"traditional lawyer."}
            </span>
          }
          <React.Fragment>{""}</React.Fragment>
        </React.Fragment>
      </p>
      <p
        className={classNames(
          projectcss.all,
          projectcss.p,
          projectcss.__wab_text,
          sty.p__dtNi4,
          {
            [sty.pothers__13Th__dtNi4Fpcpx]: hasVariant(
              $state,
              "others",
              "_13Th"
            ),
            [sty.pothers__1st__dtNi4E5Ktz]: hasVariant($state, "others", "_1st")
          }
        )}
      >
        <React.Fragment>
          <React.Fragment>{""}</React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span___8Pd8A,
                {
                  [sty.spanothers__10th___8Pd8AqLFfT]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th___8Pd8A2MkTs]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th___8Pd8AnKavM]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__1st___8Pd8Ae5Ktz]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  ),
                  [sty.spanothers__3rd___8Pd8AibNO]: hasVariant(
                    $state,
                    "others",
                    "_3rd"
                  ),
                  [sty.spanothers__4th___8Pd8AnApJo]: hasVariant(
                    $state,
                    "others",
                    "_4th"
                  ),
                  [sty.spanothers__5th___8Pd8AhEoGp]: hasVariant(
                    $state,
                    "others",
                    "_5th"
                  ),
                  [sty.spanothers__6th___8Pd8AXkkIk]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th___8Pd8An7Brb]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th___8Pd8AtQmee]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th___8Pd8AiEgyQ]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"Pragmatic,"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span___2Dl0V,
                {
                  [sty.spanothers__10th___2Dl0VqLFfT]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th___2Dl0V2MkTs]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th___2Dl0VnKavM]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__1st___2Dl0Ve5Ktz]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  ),
                  [sty.spanothers__4th___2Dl0VnApJo]: hasVariant(
                    $state,
                    "others",
                    "_4th"
                  ),
                  [sty.spanothers__5th___2Dl0VhEoGp]: hasVariant(
                    $state,
                    "others",
                    "_5th"
                  ),
                  [sty.spanothers__6th___2Dl0VXkkIk]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th___2Dl0Vn7Brb]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th___2Dl0VtQmee]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th___2Dl0ViEgyQ]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"entrepreneurial "}
            </span>
          }
          <React.Fragment>{""}</React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__aOdH,
                {
                  [sty.spanothers__10th__aOdHqLFfT]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__aOdH2MkTs]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__aOdHNKavM]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__5th__aOdHhEoGp]: hasVariant(
                    $state,
                    "others",
                    "_5th"
                  ),
                  [sty.spanothers__6th__aOdHXkkIk]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th__aOdHn7Brb]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__aOdHtQmee]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__aOdHIEgyQ]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"legal support"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__gvnvF,
                {
                  [sty.spanothers__10th__gvnvFqLFfT]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__gvnvF2MkTs]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__gvnvFnKavM]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__6th__gvnvFXkkIk]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th__gvnvFn7Brb]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__gvnvFtQmee]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__gvnvFiEgyQ]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"with heart"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__fA9I,
                {
                  [sty.spanothers__10th__fA9IqLFfT]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__fA9I2MkTs]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__fA9INKavM]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__7th__fA9In7Brb]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__fA9ItQmee]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__fA9IIEgyQ]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"and soul. "}
            </span>
          }
          <React.Fragment>{""}</React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__y4T1P,
                {
                  [sty.spanothers__10th__y4T1PqLFfT]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__y4T1P2MkTs]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__y4T1PNKavM]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__8th__y4T1PtQmee]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__y4T1PIEgyQ]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"Focused on"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__qpxah,
                {
                  [sty.spanothers__10th__qpxahqLFfT]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__qpxah2MkTs]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__qpxahNKavM]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__9th__qpxahIEgyQ]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"clear solutions"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__hWzoX,
                {
                  [sty.spanothers__10th__hWzoXqLFfT]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__hWzoX2MkTs]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__hWzoXnKavM]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__1st__hWzoXe5Ktz]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  )
                }
              )}
            >
              {"that move"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span___4Csp3,
                {
                  [sty.spanothers__11Th___4Csp32MkTs]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th___4Csp3NKavM]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  )
                }
              )}
            >
              {"your business"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__jwinb,
                {
                  [sty.spanothers__12Th__jwinbNKavM]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  )
                }
              )}
            >
              {"forward"}
            </span>
          }
          <React.Fragment>{""}</React.Fragment>
        </React.Fragment>
      </p>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  header3: ["header3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  header3: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSwitchingLetters__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSwitchingLetters__VariantsArgs;
    args?: PlasmicSwitchingLetters__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSwitchingLetters__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSwitchingLetters__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSwitchingLetters__ArgProps,
          internalVariantPropNames: PlasmicSwitchingLetters__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSwitchingLetters__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "header3") {
    func.displayName = "PlasmicSwitchingLetters";
  } else {
    func.displayName = `PlasmicSwitchingLetters.${nodeName}`;
  }
  return func;
}

export const PlasmicSwitchingLetters = Object.assign(
  // Top-level PlasmicSwitchingLetters renders the root element
  makeNodeComponent("header3"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicSwitchingLetters
    internalVariantProps: PlasmicSwitchingLetters__VariantProps,
    internalArgProps: PlasmicSwitchingLetters__ArgProps
  }
);

export default PlasmicSwitchingLetters;
/* prettier-ignore-end */
